# Generated by Django 2.1.1 on 2018-09-29 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilan',
            old_name='yazar',
            new_name='user',
        ),
    ]
