# Generated by Django 2.1.2 on 2018-10-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0003_auto_20181005_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilan',
            options={'permissions': (('can_edit', 'İlanını düzenleyebilir'), ('can_delete', 'İlanını silebilir'))},
        ),
    ]
