# Generated by Django 2.1.2 on 2018-10-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0004_auto_20181006_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilan',
            options={},
        ),
    ]
