# Generated by Django 2.1.2 on 2018-10-27 15:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0007_auto_20181011_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
