# Generated by Django 2.1.2 on 2018-10-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0009_auto_20181027_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilan',
            name='baslik',
        ),
    ]
