# Generated by Django 2.1.2 on 2018-10-27 17:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0010_remove_ilan_baslik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
