# Generated by Django 2.1.2 on 2018-10-27 17:16

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0011_auto_20181027_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=ckeditor.fields.RichTextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
