# Generated by Django 2.1.2 on 2018-10-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0012_auto_20181027_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilan',
            name='gosterim_sayisi',
        ),
    ]
