# Generated by Django 2.1.2 on 2018-10-27 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0013_remove_ilan_gosterim_sayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
