# Generated by Django 2.1.2 on 2018-10-27 18:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0014_auto_20181027_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=ckeditor.fields.RichTextField(default='hakanalk k ejki a kake'),
            preserve_default=False,
        ),
    ]
