# Generated by Django 2.1.2 on 2018-10-28 11:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0018_auto_20181028_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
