# Generated by Django 2.1.2 on 2018-10-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0019_auto_20181028_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
