# Generated by Django 2.1.2 on 2018-10-29 07:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0020_auto_20181028_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=ckeditor.fields.RichTextField(default='jkghhgchhhh'),
            preserve_default=False,
        ),
    ]
