# Generated by Django 2.1.2 on 2018-10-29 20:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0022_auto_20181029_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
