# Generated by Django 2.1.2 on 2018-10-29 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilan', '0023_auto_20181029_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_metni', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='ilan.Ilan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sahibi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
