# Generated by Django 2.1.2 on 2018-10-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0024_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='yayinlandimi',
            field=models.BooleanField(default=False),
        ),
    ]
