# Generated by Django 2.1.2 on 2018-11-01 23:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0026_auto_20181030_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutlulukdile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='ilan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='ilan.Ilan'),
        ),
    ]
