# Generated by Django 2.1.2 on 2018-11-02 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilan', '0027_auto_20181102_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutlulukdile',
            name='ilan',
        ),
        migrations.RemoveField(
            model_name='mutlulukdile',
            name='user',
        ),
        migrations.AddField(
            model_name='mutlulukdile',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='begeniler', to=settings.AUTH_USER_MODEL),
        ),
    ]
