# Generated by Django 2.1.2 on 2018-11-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0028_auto_20181102_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutlulukdile',
            name='users_like',
        ),
        migrations.DeleteModel(
            name='MutlulukDile',
        ),
    ]
