# Generated by Django 2.1.2 on 2018-11-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0029_auto_20181102_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='baslik',
            field=models.CharField(default='baslı', max_length=30),
            preserve_default=False,
        ),
    ]
