# Generated by Django 2.1.2 on 2018-11-04 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilan', '0030_ilan_baslik'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='mutlulukdileyenler',
            field=models.ManyToManyField(related_name='mutluluk_diledikleri', to=settings.AUTH_USER_MODEL),
        ),
    ]
