# Generated by Django 2.1.2 on 2018-11-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0031_ilan_mutlulukdileyenler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilan',
            old_name='mutlulukdileyenler',
            new_name='mutluluk_dileyenler',
        ),
    ]
