# Generated by Django 2.1.2 on 2018-11-05 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilan', '0032_auto_20181105_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutlulukDile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('users_like', models.ManyToManyField(blank=True, related_name='begeniler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ilan',
            name='mutluluk_dileyenler',
            field=models.ManyToManyField(related_name='mutluluk_diledikleri', to='ilan.MutlulukDile'),
        ),
    ]
