# Generated by Django 2.1.2 on 2018-11-05 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilan', '0034_auto_20181105_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutlulukdile',
            name='users_like',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='mutluluk_dile',
        ),
        migrations.AddField(
            model_name='ilan',
            name='mutluluk_dileyenler',
            field=models.ManyToManyField(related_name='mutluluk_dilenen_ilan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MutlulukDile',
        ),
    ]
