# Generated by Django 2.1.2 on 2018-11-06 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0035_auto_20181105_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='mutluluk_dileyenler',
            field=models.ManyToManyField(blank=True, related_name='mutluluk_dilenen_ilan', to=settings.AUTH_USER_MODEL),
        ),
    ]
