# Generated by Django 2.1.2 on 2018-11-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0036_auto_20181106_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='goruntulenme',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
