# Generated by Django 2.1.2 on 2018-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0037_comment_goruntulenme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='goruntulenme',
        ),
        migrations.AddField(
            model_name='ilan',
            name='goruntulenme',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
