# Generated by Django 2.1.2 on 2018-11-11 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0038_auto_20181109_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='ilan_foto',
            field=models.ImageField(default=datetime.datetime(2018, 11, 11, 21, 6, 4, 269271, tzinfo=utc), upload_to='ilan_fotolari'),
            preserve_default=False,
        ),
    ]
