# Generated by Django 2.1.2 on 2018-11-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0040_auto_20181112_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='ilan_foto',
            field=models.ImageField(default='350x150.png', upload_to='ilan_fotolari/'),
        ),
    ]
