# Generated by Django 2.1.2 on 2018-12-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0043_auto_20181125_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='ilan_fon_muzik',
            field=models.FileField(blank=True, upload_to='ilan_fon_muzikleri/'),
        ),
    ]
