# Generated by Django 2.1.2 on 2018-12-21 14:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0044_ilan_ilan_fon_muzik'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='arkaplan_rengi',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
    ]
