# Generated by Django 2.1.2 on 2018-12-21 23:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0045_ilan_arkaplan_rengi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=tinymce.models.HTMLField(),
        ),
    ]
