# Generated by Django 2.1.2 on 2018-12-21 23:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0046_auto_20181222_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=tinymce.models.HTMLField(verbose_name='İlan Metni'),
        ),
    ]
