# Generated by Django 2.1.4 on 2018-12-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0046_ilan_arkaplan_resmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='metin',
            field=models.TextField(blank=True),
        ),
    ]
